manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
  defaults:
    remote: zephyrproject

  projects:
    # Zephyr repository (specific tag or branch)
    - name: zephyr
      path: zephyr
      revision: v3.6.0
      import: true  # Pull in Zephyr modules automatically
    - name: cmsis
      revision: 4b96cbb174678dcd3ca86e11e1f24bc5f8726da0
      path: modules/hal/cmsis
      groups:
        - hal
    - name: hal_nordic
      revision: dce8519f7da37b0a745237679fd3f88250b495ff
      path: modules/hal/nordic
      groups:
        - hal

  self:
    path: .