manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos

  projects:
    # Zephyr repository (specific tag or branch)
    - name: zephyr
      path: zephyr
      remote: zephyrproject
      revision: v3.6.0
      import: true  # Pull in Zephyr modules automatically

  self:
    path: .